# Generated by Django 5.0.1 on 2026-02-10 04:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True, help_text='UUID of the user', verbose_name='User ID')),
                ('role', models.CharField(db_index=True, help_text='Role of the person (e.g., user, assistant, admin)', max_length=50, verbose_name='Role')),
                ('request', models.TextField(help_text="User's request/message", verbose_name='Request')),
                ('response', models.TextField(help_text="Assistant's response or error indication", verbose_name='Response')),
                ('turn_index', models.IntegerField(db_index=True, help_text='Turn number in the conversation', verbose_name='Turn Index')),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], db_index=True, default='success', help_text='Status of the chat (success or fail)', max_length=20, verbose_name='Status')),
                ('langflow_time', models.FloatField(blank=True, help_text='Time taken by Langflow API in seconds', null=True, verbose_name='Langflow Time')),
                ('total_round_trip_time', models.FloatField(blank=True, help_text='Total time from frontend to backend to Langflow and back in seconds', null=True, verbose_name='Total Round Trip Time')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Session ID used for the chat', max_length=255, null=True, verbose_name='Session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Chat Log',
                'verbose_name_plural': 'Chat Logs',
                'db_table': 'chat_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='chat_logs_user_id_50cffa_idx'), models.Index(fields=['session_id'], name='chat_logs_session_35922e_idx'), models.Index(fields=['turn_index'], name='chat_logs_turn_in_5594f1_idx'), models.Index(fields=['created_at'], name='chat_logs_created_00b4c5_idx'), models.Index(fields=['user_id', 'session_id', 'turn_index'], name='chat_logs_user_id_df7456_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the task', max_length=255, verbose_name='Task Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task', null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the task', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format', verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'db_table': 'task_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='task_logs_status_7c2561_idx'), models.Index(fields=['created_at'], name='task_logs_created_01686a_idx'), models.Index(fields=['status', 'created_at'], name='task_logs_status_4b129d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tasklog',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'in_progress', 'completed', 'failed', 'cancelled'])), name='valid_status'),
        ),
    ]
