# Generated by Django 5.0.1 on 2026-02-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_chatlog_final_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='generated_answer',
            field=models.TextField(help_text="Assistant's response or error indication", verbose_name='Generated Answer'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user_prompt',
            field=models.TextField(help_text="User's request/message", verbose_name='User Prompt'),
        ),
    ]
